Import("env")
Import("tag")
def make_objs(file_list, suffix, enviroment) :
    return [ enviroment.SharedObject(file + '-' + suffix + '.os', file + '.cpp' ) for file in file_list ]

files = Split('proteus prot')
objs = make_objs(files, tag, env)
Return('objs')